<H1>Server Terms Of Service (T.O.S)</H1>

<H2>1. Inactive Servers</H2>

<H3>If you paid for a server but you aren't letting anybody use it, your server will be free until you use up your monthly storage amount</H3>
<H3>If a server uses up all available storage, servers will be closed for everybody until you pay for it again</H3>
<H3>Your server will be deleted if it is inactive for over 25 years unless it has over 1000000 likes or more</H3>

<H2>2. Server Data</H2>

<H3>All data on your servers is permanent, deleting stuff will delete it off your server but it will remain on our servers</H3>
<H3>Even after you delete content, it still counts as your storage memory</H3>

<H2>3. Illegal Activity</H2>

<H3>If you create public servers, there are ALOT more rules</H3>
<H3>If you have illegal activity going on (such as casinos, scamming, threats, ransom, piracy) whoever left the content will be kicked from the server and will be banned from ALL servers for a year</H3>

<H2>4. Inappropriate Bio</H2>

<H3>Your Bio Is meant to describe your server and who is in it</H3>
<H3>You cannot leave hate towards anyone in your bio</H3>
<H3>If you have malicious, piracy, illegal data, ransom, scam, or third party content links, your server will be suspended, and you will lose access to your server for up to 2 years</H3>

<H2>5. Inappropriate Images</H2>

<H3>Servers like hospital, school, or bank, even though they are private, you are not allowed to have inappropriate content posted in it</H3>
<H3>Our algorithm detects inappropriate content, and it will be taken down and your account will be suspended</H3>
<H3>You do NOT want to do this, because if your job requires this server, you might lose your job</H3>
<H3>Inappropriate content includes</H3>
<H3>1. Nudity</H3>
<H3>2. Too Much Gore</H3>
<H3>3. Threats and desceptive acts</H3>
<H3>4. Third party content</H3>
<H3>5. Pointless images (like solid color images)</H3>

<H2>6. Underage Server Members</H2>

<H3>Servers with voice chat are age restricted, that doesn't mean a kid can sneak in</H3>
<H3>Examples of a kid getting in is like a kid getting access to their parent/guardians account</H3>
<H3>This also means that you cannot say the following</H3>
<H3>1. Cursing</H3>
<H3>2. Threats</H3>
<H3>3. Constant Screaming</H3>
<H3>4. Sexual Noises</H3>
<H3>5. Violent Noises</H3>
<H3>6. Third party Audio and music</H3>
<H3>7. Dirty talking</H3>
<H3>Due to privacy reasons, our servers do not detect audio through our algorithm so you have to be very careful</H3>
<H3>If you want your children to be safe, you should disable voice chat or find a server that doesn't have voice chat</H3>
<H3>Please watch your kids</H3>

<H2>7. Profanity</H2>

<H3>You should use the profanity filter</H3>
<H3>Every Server Has it</H3>
<H3>If you are making a video with profanity, you can turn it off</H3>
<H3>However it is not recommended to use profanity in business servers to prevent losing your job</H3>

<H2>8. Piracy and third party content</H2>

<H3>We do not have the rights of repurposing or reproducing copyrighted content</H3>
<H3>To be even more safe, fair use requires account verification</H3>
<H3>Using copyright content on ANY server results in a ban and an account suspension</H3>
<H3>Repeat offenses result in account termination</H3>
<H3>Piracy is a very bad thing to do</H3>
<H3>Even on private servers, you should NEVER pirate ANYTHING</H3>
<H3>Piracy can result in a up to $250000.00 fine and up to 5 years in federal prison</H3>
<H3>We cannot protect you against this law so be careful</H3>

<H2>Thank you for reading the server T.O.S</H2>